---
kind: pipeline
type: docker
name: default

trigger:
  branch:
   - ko
  event:
   - push
   - tag

steps:
  - name: lint
    image: golangci/golangci-lint
    pull: if-not-exists
    commands:
      - golangci-lint run
  
  - name: wait for db
    image: mariadb
    commands:
      - until mariadb-admin --host=mysql --user=demo --password=password --port=3306 ping; do sleep 3; done;
  
  - name: test
    image: golang:1.18
    pull: if-not-exists
    environment:
      FRUITS_DB_TYPE: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: superS3cret!
      MYSQL_PASSWORD: pa55Word!
      MYSQL_USER: demo
      MYSQL_DATABASE: demodb
    commands:
      - go clean -testcache
      - go test -timeout 30s -v ./... 

  - name: push
    image: kameshsampath/kube-dev-tools:0.1.3
    pull: if-not-exists
    environment:
      KO_DOCKER_REPO:
        from_secret: ko_docker_repo
      IMAGE_REGISTRY_USER:
        from_secret: image_registry_user
      IMAGE_REGISTRY_PASSWORD:
        from_secret: image_registry_password
    commands:
      - |
        echo -n "$IMAGE_REGISTRY_PASSWORD" \
          | ko login docker.io -u "$IMAGE_REGISTRY_USER" --password-stdin
      - |
        ko build --platform=linux/amd64 \
          --platform=linux/arm64 \
          --bare .

services:
  - name: mysql
    image: mariadb
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: superS3cret!
      MYSQL_PASSWORD: pa55Word!
      MYSQL_USER: demo
      MYSQL_DATABASE: demodb
