---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint
    pull: if-not-exists
    commands:
      - golangci-lint run

  - name: test
    image: golang:1.18
    pull: if-not-exists
    commands:
      - go clean -testcache
      - go test ./...
    environment:
      ## override the test connection to be local
      QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongodb"

  - name: build and push
    image: kameshsampath/kube-dev-tools:0.1.4
    pull: if-not-exists
    commands:
      - echo -n "$DOCKER_HUB_PASSWORD" | ko auth login docker.io -u "$DOCKER_HUB_USERNAME" --password-stdin
      - ko build --bare --platform linux/amd64 --platform linux/arm64 .

services:
  - name: mongodb
    image: mongo
