---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint
    pull: if-not-exists
    commands:
      - golangci-lint run
  - name: test
    image: golang:1.18
    pull: if-not-exists
    commands:
      - go clean -testcache
      - go test ./... -v

  - name: Build Binaries
    image: goreleaser/goreleaser
    pull: if-not-exists
    environment:
      CGO_ENABLED: "0"
    commands:
      - goreleaser build --snapshot --rm-dist --debug
  
  - name: push image to registry
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      platforms:
        - linux/amd64
        - linux/arm64
      context: .

services:
  - name: mongodb
    image: mongo

      