project_name: fruits-api
#before:
#  hooks:
#    - go mod tidy
#    - go mod vendor
builds:
  - id: server
    main: server.go
    binary: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    flags:
      - -mod=vendor
    ldflags:
      - '-s -w -X main.build={{.Version}} -extldflags "-static"'
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: false
  prerelease: "true"
  name_template: "Release {{ .Tag }}"
