version: "3.7"
services:
  fruits-api:
    image: "${PLUGIN_REGISTRY}/${PLUGIN_REPO}:${PLUGIN_TAG}"
    ports:
      - "8080:8080"
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: "mongodb://mongodb"
      FRUIT_DB: "demodb"
      FRUITS_DB_COLLECTION: "fruits"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: demodb
networks:
  fruits-app: