version: "3.7"
services:
  fruits-api:
    image: "${PLUGIN_REGISTRY}/${PLUGIN_REPO}:${PLUGIN_TAG}"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
     - .env
networks:
  fruits-app: